[2022-10-04 15:34:07,355] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2022-09-07T03:27:30.560400+00:00 [queued]>
[2022-10-04 15:34:07,440] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2022-09-07T03:27:30.560400+00:00 [queued]>
[2022-10-04 15:34:07,442] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 15:34:07,444] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-10-04 15:34:07,448] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 15:34:07,561] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2022-09-07 03:27:30.560400+00:00
[2022-10-04 15:34:07,646] {standard_task_runner.py:52} INFO - Started process 5493 to run task
[2022-10-04 15:34:07,723] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'td-dag-test', 'get_data', 'manual__2022-09-07T03:27:30.560400+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/td_dag_test.py', '--cfg-path', '/tmp/tmpb4uo5aoy', '--error-file', '/tmp/tmpvkouvs4w']
[2022-10-04 15:34:07,747] {standard_task_runner.py:80} INFO - Job 186: Subtask get_data
[2022-10-04 15:34:08,436] {task_command.py:371} INFO - Running <TaskInstance: td-dag-test.get_data manual__2022-09-07T03:27:30.560400+00:00 [running]> on host f2e7b0d61203
[2022-10-04 15:34:08,823] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=mravelo@groupon.com
AIRFLOW_CTX_DAG_OWNER=FSA
AIRFLOW_CTX_DAG_ID=td-dag-test
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-07T03:27:30.560400+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-07T03:27:30.560400+00:00
[2022-10-04 15:34:08,828] {logging_mixin.py:115} INFO - --- INFO: Move data process started ---
[2022-10-04 15:34:08,843] {base.py:68} INFO - Using connection ID 'teradata' for task execution.
[2022-10-04 15:34:23,666] {local_task_job.py:221} WARNING - State of this instance has been externally set to None. Terminating instance.
[2022-10-04 15:34:23,691] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 5493. PIDs of all processes in the group: [5493]
[2022-10-04 15:34:23,700] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 5493
[2022-10-04 15:34:30,399] {process_utils.py:75} INFO - Process psutil.Process(pid=5493, status='terminated', exitcode=<Negsignal.SIGABRT: -6>, started='15:34:07') (5493) terminated with exit code Negsignal.SIGABRT
