[2022-10-04 15:34:09,190] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2022-09-07T03:29:26.439473+00:00 [queued]>
[2022-10-04 15:34:09,226] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2022-09-07T03:29:26.439473+00:00 [queued]>
[2022-10-04 15:34:09,228] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 15:34:09,230] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-10-04 15:34:09,232] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 15:34:09,328] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2022-09-07 03:29:26.439473+00:00
[2022-10-04 15:34:09,354] {standard_task_runner.py:52} INFO - Started process 5546 to run task
[2022-10-04 15:34:09,378] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'td-dag-test', 'get_data', 'manual__2022-09-07T03:29:26.439473+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/td_dag_test.py', '--cfg-path', '/tmp/tmpng2dnmwa', '--error-file', '/tmp/tmp5bbhyp_5']
[2022-10-04 15:34:09,382] {standard_task_runner.py:80} INFO - Job 187: Subtask get_data
[2022-10-04 15:34:09,745] {task_command.py:371} INFO - Running <TaskInstance: td-dag-test.get_data manual__2022-09-07T03:29:26.439473+00:00 [running]> on host f2e7b0d61203
[2022-10-04 15:34:10,179] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=mravelo@groupon.com
AIRFLOW_CTX_DAG_OWNER=FSA
AIRFLOW_CTX_DAG_ID=td-dag-test
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-07T03:29:26.439473+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-07T03:29:26.439473+00:00
[2022-10-04 15:34:10,191] {logging_mixin.py:115} INFO - --- INFO: Move data process started ---
[2022-10-04 15:34:10,235] {base.py:68} INFO - Using connection ID 'teradata' for task execution.
[2022-10-04 15:34:20,576] {local_task_job.py:221} WARNING - State of this instance has been externally set to None. Terminating instance.
[2022-10-04 15:34:20,828] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 5546. PIDs of all processes in the group: [5546]
[2022-10-04 15:34:20,873] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 5546
[2022-10-04 15:34:25,683] {process_utils.py:75} INFO - Process psutil.Process(pid=5546, status='terminated', exitcode=143, started='15:34:09') (5546) terminated with exit code 143
