[2022-10-04 15:32:38,660] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2022-09-07T02:02:24.511338+00:00 [queued]>
[2022-10-04 15:32:38,750] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2022-09-07T02:02:24.511338+00:00 [queued]>
[2022-10-04 15:32:38,753] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 15:32:38,755] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-10-04 15:32:38,764] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 15:32:38,877] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2022-09-07 02:02:24.511338+00:00
[2022-10-04 15:32:38,917] {standard_task_runner.py:52} INFO - Started process 5132 to run task
[2022-10-04 15:32:39,042] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'td-dag-test', 'get_data', 'manual__2022-09-07T02:02:24.511338+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/td_dag_test.py', '--cfg-path', '/tmp/tmpnt6boscr', '--error-file', '/tmp/tmp0i8yruv3']
[2022-10-04 15:32:39,086] {standard_task_runner.py:80} INFO - Job 179: Subtask get_data
[2022-10-04 15:32:39,713] {task_command.py:371} INFO - Running <TaskInstance: td-dag-test.get_data manual__2022-09-07T02:02:24.511338+00:00 [running]> on host f2e7b0d61203
[2022-10-04 15:32:41,432] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=mravelo@groupon.com
AIRFLOW_CTX_DAG_OWNER=FSA
AIRFLOW_CTX_DAG_ID=td-dag-test
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-07T02:02:24.511338+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-07T02:02:24.511338+00:00
[2022-10-04 15:32:41,591] {logging_mixin.py:115} INFO - --- INFO: Move data process started ---
[2022-10-04 15:32:41,626] {base.py:68} INFO - Using connection ID 'teradata' for task execution.
[2022-10-04 15:33:53,871] {logging_mixin.py:115} INFO - we came back from Teradata
[2022-10-04 15:33:54,362] {logging_mixin.py:115} INFO -     environment_id  ...     last_modified_by
0           10001  ...  EMERGENOW\brobinson
1               1  ...  EMERGENOW\brobinson
2           20001  ...  EMERGENOW\brobinson

[3 rows x 17 columns]
[2022-10-04 15:33:54,368] {logging_mixin.py:115} INFO - --- INFO: Move data process complete ---
[2022-10-04 15:33:54,371] {logging_mixin.py:115} INFO - --- INFO: CSV file created ---
[2022-10-04 15:33:54,440] {python.py:173} INFO - Done. Returned value was: None
[2022-10-04 15:33:54,879] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=td-dag-test, task_id=get_data, execution_date=20220907T020224, start_date=20221004T153238, end_date=20221004T153354
[2022-10-04 15:33:56,815] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-10-04 15:33:56,928] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 5132. PIDs of all processes in the group: [5132]
[2022-10-04 15:33:56,938] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 5132
[2022-10-04 15:34:00,981] {process_utils.py:75} INFO - Process psutil.Process(pid=5132, status='terminated', exitcode=0, started='15:32:38') (5132) terminated with exit code 0
